name: webapp-testing
on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install Node dependencies
      run: cd frontend && npm install
    - name: Set up Python 3.xx
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools 
        pip install -e api/
    - name: Add OpenSearch Environment Variables
      env:
        OPENSEARCH_USERNAME: ${{ secrets.OPENSEARCH_USERNAME }}
        OPENSEARCH_PASSWORD: ${{ secrets.OPENSEARCH_PASSWORD }}
      run: |
        echo "OPENSEARCH_USERNAME=$OPENSEARCH_USERNAME" > ./api/src/mirrsearch/api/.env
        echo "OPENSEARCH_PASSWORD=$OPENSEARCH_PASSWORD" > ./api/src/mirrsearch/api/.env
    - name: Call Makefile to test and lint
      run: |
        make
